---
title: "First task"
author: "Akvilė Višniauskaitė ir Ieva Pudžiuvelytė"
date: "3/11/2022"
output: pdf_document
bibliography: references.bib
csl: apa-single-spaced.csl
---

# Introduction

This work will present data analysis from a research that studied the 
enchancer's at *IGF2* differential methylation association with abnormal 
dopamine synthesis in major psychosis [@pai2019differential].

Our samples were taken from the prefrontal cortex isolated neurons in 
schizophrenia and bipolar disorder.

Study analysed data from individuals diagnosed with schizophrenia, bipolar
disorder and controls (29, 26 and 27 individuals, respectively).
In the analysis study controlled for age, sex, post-mortem interval, genetic 
ancestry (determined by genotyping the same individuals).

## Experiment design

The experiment design was multi-omics study with 55 cases (with schizophrenia or
bipolar disorder) and 27 controls.

## Objective of the research

According to authors, schizophrenia and bipolar disorder have got characteristic 
of periods of psychosis. The main objective of the research was to gather 
epigenomic profiling data to get a more accurate model of neuronal 
dysregulation in diseases with periods of psychosis.

## Biological targets of the research

Researchers intended to look for specific patters of DNA methylation in 
isolated neurons from the frontal cortex of individuals that had diseases.

- IGF2 - insulin growth factor 2 protein
- *IGF2* - IGF2 gene
- *Igf2* - enhancer of *IGF2*
- TH - tyrosine hydroxylase protein
- dopamine - a neuromodulatory molecule
- psychosis - an abnormal condition of the mind that results in difficulties 
  determining what is real and what is not real 

## Results received

Authors found a strong association between methylation of *Igf2* and TH 
synthesis. 
TH is the bottleneck enzyme that is responsible for dopamine synthesis. 
If enhancer *Igf2* is hypomethylated, levels of TH are higher, which 
determines the higher production
of dopamine. Apparently, dopamine is responsible for psychosis in the 
mental disorders of interest.

## Additional information

Schizophrenia and bipolar disorder patients are consistently hypomethylated
at *IGF2* locus when compared to controls. This locus remained significantly 
hypomethylated even after accounting lifestyle-related variables of smoking
and anti-psychotic use.

The reaction chain of interest of the research (upward arrows show elevated
expression or synthesis of the protein, product, or effect):

Hypomethylation of *Igf2* $\rightarrow$ $\uparrow$ IGF2 $\rightarrow$ 
$\uparrow$ TH $\rightarrow$ $\uparrow$ dopamine $\rightarrow$ $\uparrow$ 
psychosis

# Data preparation

```{r}
sample_keys <- read.csv('../data/GSE112179.csv')

# Columns names in lower case
colnames(sample_keys)[5] <- tolower(colnames(sample_keys)[5])

# Unknown values
sample_keys$pmi[sample_keys$pmi == "unknown"] <- NA_real_
sample_keys$pmi[sample_keys$pmi == "?"] <- NA_real_
sample_keys$race[sample_keys$race == "?"] <- NA_character_

# Lower case
sample_keys$race <- tolower(sample_keys$race)
sample_keys$sex <- tolower(sample_keys$sex)
sample_keys$diagnosis <- tolower(sample_keys$diagnosis)

sample_keys
```

Sample keys heading is made of the following columns names:

- *id* - an identifier of the sample
- *sentrix_id* - Illumina's Sentrix BeadChip identifier 
  (`r length(unique(sample_keys$sentrix_id))` unique values) 
  [@imatsentrix]
- *sentrix_row* - row number in the Sentrix array
- *sentrix_col* - column number in the Sentrix array
- *basename* - sample identifier in the research (joined values in a format:
  \newline [*id*]_[*sentrix_id*]_R0[*sentrix_row*]C0[*sentrix_id*])
- *tissue_bank_id* - an identifying number of the tissue bank from which the 
  sample was taken
- *tissue_bank* - the literal identifier of the tissue bank
- *tissue* - a tissue type from which the sample was taken
- *cell_type* - a cell type found in the sample
- *donor* - an integer number that identifies the donor of the sample 
  (`r length(unique(sample_keys$donor))` unique values)
- *pmi* - a post-mortem interval (time units???????????), unknown values were
  labeled as NA
- *race* - a race of the donor (white, black, hispanic, or unknown (NA))
- *sex* - a gender of the donor
- *diagnosis* - an experimental group of the patient (bipolar, schizophrenia, or
  control)
- *age* - an age of the donor (years)
  
As it was noted in the article, there were 100 records in the sample keys 
dataset.

# References {-}

